[1847 AE] Move to production
tobymao/18xx pull request #10599
Opened 2024-04-03 18:43 UTC by Galatolol

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

## Implementation Notes

### Explanation of Change

Move to production since there weren't any new issues for a few months.

2024-04-03 19:22 UTC, ollybh requested changes

2024-04-03 19:22 UTC, ollybh commented on assets/app/view/welcome.rb
> +        <p><a href="https://github.com/tobymao/18xx/wiki/18NL">1847 AE</a> is in production.</p>
Wrong URL for wiki page.
```suggestion
        <p><a href="https://github.com/tobymao/18xx/wiki/1847-AE">1847 AE</a> is in production.</p>
```

2024-04-04 10:24 UTC, Galatolol commented on assets/app/view/welcome.rb
> +        <p><a href="https://github.com/tobymao/18xx/wiki/18NL">1847 AE</a> is in production.</p>
Thanks, fixed.

2024-04-04 12:14 UTC, ollybh reviewed
@Galatolol There is one open issue for 1847: #10473. It would be best to fix this (or close it if it's invalid) before moving this game to production.

2024-04-08 09:42 UTC, Galatolol commented
Ah, I missed that issue. So I'll close the PR for now.

2024-04-08 09:43 UTC, closed without merging