[1849] modification to code for variants
tobymao/18xx pull request #11417
Opened 2024-12-23 20:48 UTC by philcampeau

Hopefully fixes issues with Variants rules. I'll manually close the bug reports after confirming. (see below)

## Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

## Implementation Notes

### Explanation of Change

Players trying the variants have all encountered variations of this error at various points: 

Often, refreshing and trying again and again seems to resolve the issue temporarily, but that's obviously not a solution. This issue has proven difficult to troubleshoot, since it doesn't happen in Hotseat mode, or even when playing multiplayer on my local environment.

I tried changing the code for def operating_round, removing the logic that gates the inclusion of the variant steps, and instead adding `log_pass` and `log_skip` methods to those steps to mask those steps unless using the variants. 

Once I did this, rake would fail on the fixture files, which I found interesting since the fixture doesn't use the variants. I went through the logic of the variants themselves, and added a gate to the `def actions` to return [] if that variant isn't active. 

That resolved the Rake error, and I still seem to be able to play through local  games, so at worst this is no worse than the current state, and I think the code is cleaner and closer to the standard code seen throughout the site.

### Screenshots

### Any Assumptions / Hacks

This may well require archiving/pinning any games using the Bonds/Electric Dreams/Buy Tokens variants, but I don't believe it would affect other games of 1849.

2025-01-01 19:20 UTC, ollybh approved these changes
This change looks fine to me. I don't think that this should break any existing games as the steps will be skipped if the variants aren't selected. But leave the pins tag in place to make sure that this gets tested before the code is deployed.

2025-01-01 19:20 UTC, ollybh commented on lib/engine/game/g_1849/game.rb
>          ].compact, round_num: round_num)
You don´t need to `compact` the array any more, as it will not contain any nils.
```suggestion
        ], round_num: round_num)
```

2025-01-01 19:20 UTC, ollybh commented on lib/engine/game/g_1849/step/bond.rb
> +            print "hi #{can_take_loan?(entity)}"
A stray debugging statement has made it through to the pull request.
```suggestion
```

2025-01-01 19:20 UTC, ollybh requested changes
A couple of small fixes are needed before this gets merged.

2025-01-06 14:25 UTC, philcampeau commented on lib/engine/game/g_1849/step/bond.rb
> +            print "hi #{can_take_loan?(entity)}"
removed

2025-01-11 12:31 UTC, ollybh approved these changes

2025-01-15 12:38 UTC, merged